package probe_test

import (
	"bytes"
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/ianeff/thump/api/v1/proposal"
	"github.com/ianeff/thump/internal/probe"
)

// TestSummarize_RendersAgainstAHandWrittenFixture pins the whole fold at
// once: a mix of runs that cleared floor, one that self-reported under
// floor, and one that proposed nothing at all (Phase insufficient) — the
// three shapes a real probe sample produces. testdata/summary.golden is
// RenderSummary's exact output over that fixture, generated once and
// hand-reviewed, not regenerated by this test.
func TestSummarize_RendersAgainstAHandWrittenFixture(t *testing.T) {
	t.Parallel()

	rows := []probe.Row{
		{Run: 1, Phase: "proposed", ContractRef: "restart-cart-pod", Confidence: 0.9, Terms: proposal.ConfidenceTerms{Corroborated: 2}},
		{Run: 2, Phase: "proposed", ContractRef: "restart-cart-pod", Confidence: 0.6, Terms: proposal.ConfidenceTerms{Corroborated: 1}},
		{Run: 3, Phase: "proposed", ContractRef: "restart-cart-pod", Confidence: 0.8, Terms: proposal.ConfidenceTerms{Corroborated: 2}},
		{Run: 4, Phase: "insufficient", Reason: "no corroborating evidence"},
	}

	s := probe.Summarize(rows, 0.75)

	var got bytes.Buffer
	probe.RenderSummary(&got, s)

	want, err := os.ReadFile("testdata/summary.golden") //nolint:gosec // G304: fixed testdata path, not user input
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff(string(want), got.String()); diff != "" {
		t.Error("wrong rendered summary (-want +got)", diff)
	}
}

// TestSummarize_EmptySampleFoldsToZeroesNotDivideByZero pins that an empty
// rows slice never panics on the mean division and reports a clean N=0.
func TestSummarize_EmptySampleFoldsToZeroesNotDivideByZero(t *testing.T) {
	t.Parallel()

	s := probe.Summarize(nil, 0.75)

	if diff := cmp.Diff(probe.Summary{Floor: 0.75}, s); diff != "" {
		t.Error("wrong summary for an empty sample (-want +got)", diff)
	}
}
