package probe_test

import (
	"bytes"
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/ianeff/thump/internal/probe"
)

// TestSummarize_RendersAgainstAHandWrittenFixture pins the whole fold at
// once: a mix of runs that cleared floor, one that self-reported under
// floor, and one that proposed nothing at all — the three shapes a real
// probe sample produces. testdata/summary.golden is RenderSummary's exact
// output over that fixture, generated once and hand-reviewed, not
// regenerated by this test.
func TestSummarize_RendersAgainstAHandWrittenFixture(t *testing.T) {
	t.Parallel()

	samples := []probe.Sample{
		{Proposed: true, Confidence: 0.9, Corroborated: 2},
		{Proposed: true, Confidence: 0.6, Corroborated: 1},
		{Proposed: true, Confidence: 0.8, Corroborated: 2},
		{Proposed: false},
	}

	s := probe.Summarize(samples, 0.75)

	var got bytes.Buffer
	probe.RenderSummary(&got, s)

	want, err := os.ReadFile("testdata/summary.golden") //nolint:gosec // G304: fixed testdata path, not user input
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff(string(want), got.String()); diff != "" {
		t.Error("wrong rendered summary (-want +got)", diff)
	}
}

// TestSummarize_EmptySampleFoldsToZeroesNotDivideByZero pins that an empty
// rows slice never panics on the mean division and reports a clean N=0.
func TestSummarize_EmptySampleFoldsToZeroesNotDivideByZero(t *testing.T) {
	t.Parallel()

	s := probe.Summarize(nil, 0.75)

	if diff := cmp.Diff(probe.Summary{Floor: 0.75}, s); diff != "" {
		t.Error("wrong summary for an empty sample (-want +got)", diff)
	}
}
