// This file is generated by the opentelemetry-go-compile-instrumentation tool. DO NOT EDIT.
package main

import (
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/init"
	_ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace"

	_ "go.opentelemetry.io/otelc/instrumentation/log"

	_ "go.opentelemetry.io/otelc/instrumentation/log/slog"

	_ "go.opentelemetry.io/otelc/instrumentation/net/http/client"

	_ "go.opentelemetry.io/otelc/instrumentation/net/http/server"

	_ "go.opentelemetry.io/otelc/instrumentation/runtime"

	_otel_log "log"

	_otel_debug "runtime/debug"

	_ "unsafe"
)

//go:linkname _getstack0 go.opentelemetry.io/otelc/instrumentation/log.OtelGetStackImpl
var _getstack0 = _otel_debug.Stack

//go:linkname _printstack0 go.opentelemetry.io/otelc/instrumentation/log.OtelPrintStackImpl
var _printstack0 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack1 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace.OtelGetStackImpl
var _getstack1 = _otel_debug.Stack

//go:linkname _printstack1 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace.OtelPrintStackImpl
var _printstack1 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack2 go.opentelemetry.io/otelc/instrumentation/log/slog.OtelGetStackImpl
var _getstack2 = _otel_debug.Stack

//go:linkname _printstack2 go.opentelemetry.io/otelc/instrumentation/log/slog.OtelPrintStackImpl
var _printstack2 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack3 go.opentelemetry.io/otelc/instrumentation/net/http/client.OtelGetStackImpl
var _getstack3 = _otel_debug.Stack

//go:linkname _printstack3 go.opentelemetry.io/otelc/instrumentation/net/http/client.OtelPrintStackImpl
var _printstack3 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack4 go.opentelemetry.io/otelc/instrumentation/net/http/server.OtelGetStackImpl
var _getstack4 = _otel_debug.Stack

//go:linkname _printstack4 go.opentelemetry.io/otelc/instrumentation/net/http/server.OtelPrintStackImpl
var _printstack4 = func(bt []byte) { _otel_log.Print(string(bt)) }
