apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thump-rook-ceph-read
  namespace: rook-ceph
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thump-rook-ceph-read
  namespace: rook-ceph
subjects:
  - kind: ServiceAccount
    name: default
    namespace: thump
roleRef:
  kind: Role
  name: thump-rook-ceph-read
  apiGroup: rbac.authorization.k8s.io
