apiVersion: v1
kind: Service
metadata:
  name: rattle-metrics
  namespace: thump
  labels: {{- include "thump.labels" . | nindent 4 }}
    app.kubernetes.io/component: rattle
spec:
  selector: {{- include "thump.beatSelectorLabels" (merge (dict "component" "rattle") .) | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
