package scorecard_test

import (
	"bytes"
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/ianeff/thump/internal/scorecard"
)

// TestGrade_RendersEveryBucketAgainstAHandWrittenFixture pins the whole
// grading contract at once: testdata/results.jsonl carries one row for
// every reason scorecard can assign — a hit on both an approved and a
// refused row, a wrong verdict, a wrong contract, a non-converging approved
// row, a refusal on a row that expected to be handled (and the mirror,
// implicitly, since refusedWrongBeat is one bucket for both directions), a
// restore failure, a no-detection settle timeout, and an unrelated harness
// error — plus a repeat pass (runIndex 1) so the by-run-index breakdown has
// two rows to show. testdata/report.golden is Render's exact output over
// that fixture, generated once and hand-reviewed, not regenerated by this
// test.
func TestGrade_RendersEveryBucketAgainstAHandWrittenFixture(t *testing.T) {
	t.Parallel()

	f, err := os.Open("testdata/results.jsonl") //nolint:gosec // G304: fixed testdata path, not user input
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = f.Close() }()

	rpt, err := scorecard.Grade(f)
	if err != nil {
		t.Fatal("Grade:", err)
	}

	var got bytes.Buffer
	scorecard.Render(&got, rpt)

	want, err := os.ReadFile("testdata/report.golden") //nolint:gosec // G304: fixed testdata path, not user input
	if err != nil {
		t.Fatal(err)
	}

	if diff := cmp.Diff(string(want), got.String()); diff != "" {
		t.Error("wrong rendered report (-want +got)", diff)
	}
}

// TestGrade_SkipsBlankLinesAndCountsEveryOther pins that a trailing newline
// in a harvest --json output file (which every `tee` producing one leaves)
// doesn't inflate N by one phantom row.
func TestGrade_SkipsBlankLinesAndCountsEveryOther(t *testing.T) {
	t.Parallel()

	input := `{"scenarioName":"a","expectedVerdict":"approved","expectedContract":"c","actualVerdict":"approved","actualContract":"c","actualResult":"success","runIndex":0}

`
	rpt, err := scorecard.Grade(bytes.NewBufferString(input))
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff(1, rpt.N); diff != "" {
		t.Error("wrong row count with a trailing blank line (-want +got)", diff)
	}
	if diff := cmp.Diff(1, rpt.Hits); diff != "" {
		t.Error("wrong hit count (-want +got)", diff)
	}
}

// TestGrade_FailsOnUnparseableInputInsteadOfSilentlySkippingIt pins that a
// malformed line is a caller error, not a grading outcome — a corrupted
// results file shouldn't quietly produce a rate over a subset of its rows.
func TestGrade_FailsOnUnparseableInputInsteadOfSilentlySkippingIt(t *testing.T) {
	t.Parallel()

	_, err := scorecard.Grade(bytes.NewBufferString("not json\n"))
	if err == nil {
		t.Fatal("want an error on unparseable input, got nil")
	}
}
