// This file is generated by the opentelemetry-go-compile-instrumentation tool. DO NOT EDIT.
package main

import _ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel"
import _ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/init"
import _ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/sdk/trace"
import _ "go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace"
import _ "go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/client"
import _ "go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/server"
import _ "go.opentelemetry.io/otelc/instrumentation/log"
import _ "go.opentelemetry.io/otelc/instrumentation/log/slog"
import _ "go.opentelemetry.io/otelc/instrumentation/net/http/client"
import _ "go.opentelemetry.io/otelc/instrumentation/net/http/server"
import _ "go.opentelemetry.io/otelc/instrumentation/runtime"
import _otel_log "log"
import _otel_debug "runtime/debug"
import _ "unsafe"

//go:linkname _getstack0 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel.OtelGetStackImpl
var _getstack0 = _otel_debug.Stack

//go:linkname _printstack0 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel.OtelPrintStackImpl
var _printstack0 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack1 go.opentelemetry.io/otelc/instrumentation/log.OtelGetStackImpl
var _getstack1 = _otel_debug.Stack

//go:linkname _printstack1 go.opentelemetry.io/otelc/instrumentation/log.OtelPrintStackImpl
var _printstack1 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack2 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace.OtelGetStackImpl
var _getstack2 = _otel_debug.Stack

//go:linkname _printstack2 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/trace.OtelPrintStackImpl
var _printstack2 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack3 go.opentelemetry.io/otelc/instrumentation/log/slog.OtelGetStackImpl
var _getstack3 = _otel_debug.Stack

//go:linkname _printstack3 go.opentelemetry.io/otelc/instrumentation/log/slog.OtelPrintStackImpl
var _printstack3 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack4 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/sdk/trace.OtelGetStackImpl
var _getstack4 = _otel_debug.Stack

//go:linkname _printstack4 go.opentelemetry.io/otelc/instrumentation/go.opentelemetry.io/otel/sdk/trace.OtelPrintStackImpl
var _printstack4 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack8 go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/client.OtelGetStackImpl
var _getstack8 = _otel_debug.Stack

//go:linkname _printstack8 go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/client.OtelPrintStackImpl
var _printstack8 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack10 go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/server.OtelGetStackImpl
var _getstack10 = _otel_debug.Stack

//go:linkname _printstack10 go.opentelemetry.io/otelc/instrumentation/google.golang.org/grpc/server.OtelPrintStackImpl
var _printstack10 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack11 go.opentelemetry.io/otelc/instrumentation/net/http/client.OtelGetStackImpl
var _getstack11 = _otel_debug.Stack

//go:linkname _printstack11 go.opentelemetry.io/otelc/instrumentation/net/http/client.OtelPrintStackImpl
var _printstack11 = func(bt []byte) { _otel_log.Print(string(bt)) }

//go:linkname _getstack12 go.opentelemetry.io/otelc/instrumentation/net/http/server.OtelGetStackImpl
var _getstack12 = _otel_debug.Stack

//go:linkname _printstack12 go.opentelemetry.io/otelc/instrumentation/net/http/server.OtelPrintStackImpl
var _printstack12 = func(bt []byte) { _otel_log.Print(string(bt)) }
